require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  DisplayStyleGuide: true
  Include:
    - '**/*.rb'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'config/initializers/money.rb'

Layout/LineLength:
  IgnoredPatterns: ['\A\s*#']
  Max: 80

RSpec/ExampleLength:
  Max: 6

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'Gemfile'
    - 'config/routes.rb'
    - 'config/environments/**/*'
    - 'spec/controllers/*'

Layout/EndOfLine:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 16

Metrics/MethodLength:
  Enabled: true
  Max: 16

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'app/channels/application_cable/**/*'
    - 'config/application.rb'

Style/ClassMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/For:
  EnforcedStyle: for

Style/GuardClause:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true

Style/NegatedIf:
  EnforcedStyle: postfix

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses