name: Deploy staging

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: "71f662d8-8868-49ba-bbe4-2bcc1a00c3dc" # temporal
          heroku_app_name: "walletest-reborn"
          heroku_email: "gabriel.faundez@gmail.com"
          healthcheck: "https://walletest-reborn.herokuapp.com"
